version: '3.9'
services:
  competitionapp-api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - ms-sql-server
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "4433:1433"
#    Environment settings
#    environment:
      